 services:
   mysql:
     container_name: mysql
     image: mysql:8
     environment:
       - MYSQL_DATABASE=base
       - MYSQL_ROOT_USER=root
       - MYSQL_ROOT_PASSWORD=root
     ports:
       - "3306:3306"